### PR TITLE
Setup

### PR DESCRIPTION
**Pull request by yosefHesham**
**Changes Made:**
1- Create react app
2- setup linters

### CODE REVIEW

**Review by t-yanick — COMMENTED** [review]
Hi @yosefHesham, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is failing `Linter` checks. Please kindly fix the `Linter` errors  before you resubmit for review. 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by t-yanick — CHANGES_REQUESTED** [review]
Hi @yosefHesham, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments below and under the review._

 ### I will leave the comment here, since your `Readme file` is not accessible for this PR ### 

- [ ] Please kindly update your `readme file` to reflect the changes for this milestone as this will make your `readme file` more informative and professional. Checkout this [template](https://github.com/microverseinc/readme-template) and adapt it to your project. Replace all the information in the various sections of the template with information pertaining to your project.  

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by nicupop729** [comment]
PR under second opinion review.

Please wait for a response!

**Comment by nicupop729** [comment]
Hi @yosefHesham,

Thanks a lot for reaching out!

As a response, I must state the followings:
When we build projects, all the time we need to have for them a README file which we must create from the beginning. Actually, the missing README file is a reason for the invalidation of a PR. 

The reviewer when invalidated the first time for the failing linters should have given you the reason for missing the README file as well. I believe he realised the missing README after taking your project for review the second time and he could not invalidate the PR again, now for another reason.

It is mandatory to create a README file from the beginning, following the template that Microverse provides and fill it with as much information as we can: 
Project Name - from the beginning;
Built with - from the beginning - here we already know what technologies, languages and frameworks will use; at the end of the project, we can add more if we used more;
Live Demo - add it later;
Getting started  - from the beginning;
Prerequisites - from the beginning;
Setup - from the beginning - add information later on if needed;
Install - from the beginning - add information later on if needed;
Usage - add later if is needed;
Run tests - add later if is needed;
Deployment - add later if is needed;
Author - from the beginning, with the mention that you need to add your partners if you will work in pair-programming;
Contributing - from the beginning;
Show your support - from the beginning;
Acknowledgements - when necessary;
License - from the beginning;

I hope these clarifications help!

Please do the README file following the template from Microverse, fill it with as much info as possible, and ask again for another review!

Good luck!

**Review by KDlamini — APPROVED** [review]
### Hi @yosefHesham 🙋‍♀️,  

Geat job!
Your feature is complete! There is nothing else to say other than... it's time to merge it. :shipit: 
Congratulations!!!

# Status: Approved ✔️ 

## Important Suggestions💡 
In your README, under `setup` you can be more specific about how to clone the repository.
For example:
image

 
Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @KDlamini  in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
